/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:84cb365d-7ec6-432c-b041-3d980aba59df",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_YopCodXNd",
    "aws_user_pools_web_client_id": "5r32jpth1besfkkufkhvkt1ft5",
    "oauth": {
        "domain": "medabotsappc18a2562-c18a2562-dev.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://johannpereze.github.io/medabots-app/",
        "redirectSignOut": "https://johannpereze.github.io/medabots-app/loginhttps://johannpereze.github.io/medabots-app/login/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
